export const EXPENSE_LIST_LOADING = 'EXPENSE_LIST_LOADING';
export const EXPENSE_LIST_REFRESHING = 'EXPENSE_LIST_REFRESHING';
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS';
export const EXPENSE_LIST_ERROR = 'EXPENSE_LIST_ERROR';
export const EXPENSE_LIST_ADD_EXPENSE_LOADING = 'EXPENSE_LIST_ADD_EXPENSE_LOADING';
export const EXPENSE_LIST_ADD_EXPENSE_SUCCESS = 'EXPENSE_LIST_ADD_EXPENSE_SUCCESS';
export const EXPENSE_LIST_ADD_EXPENSE_ERROR = 'EXPENSE_LIST_ADD_EXPENSE_ERROR';
